// template-vue/playground/src/App.vue
<script setup lang="ts">
import { MyButton } from '../../src';
</script>

<template>
  <div>
    <a href="https://rolldown.rs" target="_blank" rel="noopener noreferrer">
      <img src="/rolldown.svg" class="logo" alt="Rolldown logo" />
    </a>
  </div>
  <h1>Rolldown + Vue</h1>
  <div class="card">
    <MyButton />
  </div>
  <p class="read-the-docs">
    Click on the Rolldown logo to learn more
  </p>
</template>

// template-react/playground/src/App.tsx
import { MyButton } from '../../src';

export function App() {
  return (
    <>
      <div>
        <a href="https://rolldown.rs" target="_blank" rel="noopener noreferrer">
          <img src="/rolldown.svg" className="logo" alt="Rolldown logo" />
        </a>
      </div>
      <h1>Rolldown + React</h1>
      <div className="card">
        <MyButton />
      </div>
      <p className="read-the-docs">Click on the Rolldown logo to learn more</p>
    </>
  );
}
